# Generated by Django 3.2.5 on 2022-05-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('emisor', models.TextField()),
                ('receptor', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_login', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('mensajes_enviados', models.ManyToManyField(related_name='mensajes_enviados', to='chat.Mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('mensajes', models.ManyToManyField(to='chat.Mensaje')),
            ],
        ),
    ]
