# Generated by Django 3.2.5 on 2022-05-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='usuarios',
            field=models.ManyToManyField(to='chat.Usuario'),
        ),
    ]
