# Generated by Django 3.2.5 on 2022-05-16 01:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_canal_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='canal',
            name='usuarios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None),
        ),
    ]
