# Generated by Django 3.2.5 on 2022-06-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_mensaje_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='correo',
            field=models.EmailField(blank=True, max_length=256),
        ),
    ]
