# Generated by Django 3.2.5 on 2022-05-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_canal_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='descripcion',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='canal',
            name='nombre',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
