# Generated by Django 3.2.5 on 2022-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(blank=True, max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='canal',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='canal',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='user',
            field=models.CharField(max_length=1000),
        ),
    ]
