# Generated by Django 3.2.5 on 2022-05-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20220516_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='mensajes_enviados',
        ),
    ]
