# Generated by Django 3.2.5 on 2022-06-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20220606_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canal',
            old_name='nombre',
            new_name='name',
        ),
    ]
