# Generated by Django 3.2.5 on 2022-05-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_remove_usuario_mensajes_enviados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='mensajes',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='usuarios',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(default='no one', on_delete=django.db.models.deletion.PROTECT, related_name='emisor_msg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
