# Generated by Django 3.2.5 on 2022-05-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='canal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.canal'),
        ),
    ]
